### ISSUE TITLE
KeyError: 'policy_name'

### ISSUE THREAD

**Issue by mwarkentin** [cloudpassage/jira_halo_issues_sync#83]
Hey @ashmastaflash , back with another one for you. I just noticed that our lambda has been erroring out with the following error - not sure of the cause.

```
[INFO]	2019-06-12T19:02:43.429Z	81080cc5-1147-4e83-a1ce-6dc500f6dca6	Creating Jira issue for Halo issue ID 44a267a48b7811e9966f4b10422905ce
[INFO]	2019-06-12T19:02:43.429Z	81080cc5-1147-4e83-a1ce-6dc500f6dca6	Halo ID: 44a267a48b7811e9966f4b10422905ce	Module: sva	Action: create
[DEBUG]	2019-06-12T19:02:43.429Z	81080cc5-1147-4e83-a1ce-6dc500f6dca6	Halo ID: 44a267a48b7811e9966f4b10422905ce	Module: sva	Action: create	Instructions: None
'policy_name': KeyError
Traceback (most recent call last):
  File "/var/task/application.py", line 75, in lambda_handler
    return main()
  File "/var/task/application.py", line 51, in main
    jlib.Reconciler.reconcile_marching_orders(config, marching_orders)
  File "/var/task/jlib/reconciler.py", line 59, in reconcile_marching_orders
    pool.map(reconciler_helper, this_batch)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
KeyError: 'policy_name'
```

The only reference I can find to it is this in `mapper.py` (but I have yet to wrap my head around how the mapping works in practice):

```
issue_mapping = {"issue_critical": "critical",
                         "issue_created_at": "created_at",
                         "issue_rule_key": "rule_key",
                         "issue_type": "issue_type",
                         "issue_id": "id",
                         "issue_policy_name": "policy_name"}
```

**Comment by ashmastaflash** [comment]
Thanks for reaching out @mwarkentin I'm looking into this now.

**Comment by mwarkentin** [comment]
Oh, I tried deploying latest master as well, no luck.

**Comment by ashmastaflash** [comment]
In this particular case, the SVA scan does not actually have a policy associated with it.

I'm working on a fix that will prevent failure on missing keys in the json.

**Comment by mwarkentin** [comment]
Sounds good, thanks!

**Comment by ashmastaflash** [comment]
Hey @mwarkentin feel free to test the develop branch to make sure it addresses your issue.

**Comment by mwarkentin** [comment]
@ashmastaflash Confirmed that the change fixed the issue for us, and we were able to complete a sync successfully.

**Comment by ashmastaflash** [comment]
That's great news on a Friday afternoon :-)
Thanks for taking the time to test!
